// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Spice.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// RetrieveAuditDetailsResponse
    /// </summary>
    public partial class MicrosoftDynamicsCRMRetrieveAuditDetailsResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveAuditDetailsResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveAuditDetailsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveAuditDetailsResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveAuditDetailsResponse(MicrosoftDynamicsCRMAuditDetail auditDetail = default(MicrosoftDynamicsCRMAuditDetail))
        {
            AuditDetail = auditDetail;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AuditDetail")]
        public MicrosoftDynamicsCRMAuditDetail AuditDetail { get; set; }

    }
}
