// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Spice.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of spice_essprocess
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.spice_essprocessCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMspiceEssprocessCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMspiceEssprocessCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMspiceEssprocessCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMspiceEssprocessCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMspiceEssprocessCollection(IList<MicrosoftDynamicsCRMspiceEssprocess> value = default(IList<MicrosoftDynamicsCRMspiceEssprocess>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMspiceEssprocess> Value { get; set; }

    }
}
