// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Spice.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// rwb_CustomiseRibbonResponse
    /// </summary>
    public partial class MicrosoftDynamicsCRMrwbCustomiseRibbonResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrwbCustomiseRibbonResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMrwbCustomiseRibbonResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrwbCustomiseRibbonResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMrwbCustomiseRibbonResponse(string result = default(string))
        {
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Result")]
        public string Result { get; set; }

    }
}
