// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Spice.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of spice_contact_account
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.spice_contact_accountCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMspiceContactAccountCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMspiceContactAccountCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMspiceContactAccountCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMspiceContactAccountCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMspiceContactAccountCollection(IList<MicrosoftDynamicsCRMspiceContactAccount> value = default(IList<MicrosoftDynamicsCRMspiceContactAccount>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMspiceContactAccount> Value { get; set; }

    }
}
