// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Spice.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of spice_previousaddresseses
    /// </summary>
    public partial class PreviousaddressesesGetResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PreviousaddressesesGetResponseModel class.
        /// </summary>
        public PreviousaddressesesGetResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PreviousaddressesesGetResponseModel class.
        /// </summary>
        public PreviousaddressesesGetResponseModel(IList<MicrosoftDynamicsCRMspicePreviousaddresses> value = default(IList<MicrosoftDynamicsCRMspicePreviousaddresses>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMspicePreviousaddresses> Value { get; set; }

    }
}
