name: spd-ess-portal

on:
  workflow_dispatch:
env:
  IMAGE_NAME: spd-ess-portal
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}
  WORKING_DIRECTORY: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        run: |
          echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login -u serviceaccount --password-stdin ${{ secrets.OCP4_REGISTRY }}

      - name: Build and push spd-ess-portal
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}


